name: CI
on:
  push:
    branches:
      - main
      - feature/**
      - phase2_indicators       # <--- NEU: Eigenen Branch hier hinzufügen!
  pull_request:
    branches:
      - main
      - feature/**
      - phase2_indicators       # <--- Optional: Auch für PRs auf diesen Branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # (rest wie gehabt)
