# Supabase-Datenbank-URL
#DATABASE_URL="postgresql://postgres.rmjvbadnwrgduojlasas:Y0yZz3J12XKKyH9N@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require"
DATABASE_URL="postgresql://postgres.rmjvbadnwrgduojlasas:VeIE5a6afpTw2B3r@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require"